
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  web:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - LEADERBOARD_SECRET=dev-secret
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  dbdata:
